Amazing Numbers Project
mackow1/jetbrains-projects pull request #5
Opened 2022-11-23 13:25 UTC by mackow1

Wrzucam projekt Amazing Numbers. Podeślę opis na maila.

2022-11-23 19:11 UTC, Y0ucandev requested changes

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        for (int i : nums) {
dwa razy robisz ta sama petle. Niepotrzebnie 
mozna to wrzucic w jedna skoro i tak tam zadnych specyficznych warunkow nie ma

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +            for (int i = 0; i < numbers.length; i++) {
pomysl jak te dwie petle polaczyc w jedna. moze sie da

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        //System.out.println(numArr);
usun pozniej ten komentarz ktory nic nie wnosi do kodu

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        //System.out.println(squared);
ten tez, i kazdy ktory jest zakomentowana java. 
Ogolnie komentarzy powinno wcale nie byc. Ale na etapie nauki je dopuszczam. Pod warunkiem ze nie komentujesz kodu javy tylko sobie costam notujesz

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +            System.out.println(input.add(BigInteger.valueOf(i)) + " is" + attached.deleteCharAt(attached.length() - 1));
po co budujesz ten input 30 ifami jezeli potem nie jest on uzyty? Albo przynajmniej nie widze zeby byl

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        if (this.isBuzz(input)) attached.append(" buzz,");
rozumiem ze tu nie ma switcha poniewaz moze wejsc z jednego inputa w X ifow ?

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/Main.java
> +                case "EVEN":
po co ten pusty switch ?

2022-11-23 19:11 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/Main.java
> +        while (true) {
takich rzeczy nie robimy. Bo ta petla leci w nieskonczonosc. Chyba ze napotka na break;
Lepiej zrobic warunek boolean conitue = true;
A potem zmienic na false jak ma przestac. A takich dziwactw typu while(true) nie robimy

2022-11-23 22:57 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +            System.out.println(input.add(BigInteger.valueOf(i)) + " is" + attached.deleteCharAt(attached.length() - 1));
Jest to użyte w opcji gdzie podajemy 2 liczby. Linijka 119 w Main. Faktycznie zastanawiałem się czy by nie połączyć z metodą poniżej. Tzn zostawić tylko tę z for i porostu tam gdzie nie potrzebuje wielu sprawdzeń, jako default podawać drugą liczbę 1, żeby tylko raz iterowało przez fora.

2022-11-23 22:57 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        if (this.isBuzz(input)) attached.append(" buzz,");
tak, tak jak powyższa metoda

2022-11-23 23:00 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/Main.java
> +                case "EVEN":
zamysł był żeby sprawdzić czy input usera jest zgodny z tym co jest możliwe. Faktycznie zastanawiałem się jak to zrobić sensownie i próbowałem tutaj z enumem, jakoś mi nie poszło i chyba zostałem przy tym switchu

2022-11-23 23:03 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/Main.java
> +        while (true) {
okay

2022-11-23 23:06 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        //System.out.println(squared);
faktycznie zapomniałem pousuwać, to moje prymitywne szukanie błędów

2022-11-23 23:12 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        for (int i : nums) {
done

2022-11-23 23:12 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +            for (int i = 0; i < numbers.length; i++) {
done

2022-11-23 23:33 UTC, mackow1 commented
poprawione wszystko, ale się skonfliktowałem... :d

2022-11-24 08:08 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +            System.out.println(input.add(BigInteger.valueOf(i)) + " is" + attached.deleteCharAt(attached.length() - 1));
Im wiecej funkcji tym zazwyczaj lepiej, oraz zawsze im mniej kodu tym lepiej, pod warunkiem ze jest on czytelny

2022-11-24 08:09 UTC, Y0ucandev commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        for (int i : nums) {
chyba nie pushnales. Bo jest tylko jeden commit w tym PR a powinny byc co najmniej 2

2022-11-24 11:39 UTC, mackow1 commented on Amazing Numbers/AmazingNumbers/src/main/java/org/example/CheckNumbers.java
> +        for (int i : nums) {
teraz chyba jest, przynajmniej mi się wyświetla że są jakieś zmiany

2022-11-24 15:24 UTC, Y0ucandev approved these changes

2022-11-24 15:24 UTC, merged